In [2]:
import pandas as pd

df_busan = pd.read_csv("C:/Users/Admin/Desktop/새 폴더/LOCAL_PEOPLE_DONG_202506.csv")

In [3]:
df_busan

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
20250601,0,11170690,13016.4691,504.7423,363.9773,342.0560,337.4781,339.0929,355.4220,461.7653,...,399.1142,520.9040,587.5097,732.9256,514.2931,483.9796,438.7389,240.5809,863.7506,NaN
20250601,0,11260660,12465.4868,402.3057,206.1997,239.6375,357.8616,408.9449,452.2764,476.4358,...,459.6757,531.0848,388.4666,449.5039,527.5349,652.8474,544.2389,430.7135,1053.8818,NaN
20250601,0,11620735,27735.1490,357.5485,181.0755,530.2556,2359.6018,2696.8200,1734.1525,1690.5205,...,1049.6378,901.2637,592.0158,622.0435,517.7347,595.2660,481.9500,456.4447,1158.2406,NaN
20250601,0,11290640,14738.4304,273.6058,141.1779,686.0608,1731.1215,953.6577,456.2677,456.6890,...,417.7809,390.1571,364.7812,383.8952,393.9166,460.7497,348.3016,284.1729,857.1534,NaN
20250601,0,11215830,24319.6994,969.6121,453.5985,476.9419,628.6852,804.5160,1005.6726,1177.3467,...,1107.2734,1341.2972,1033.9218,1038.4024,859.3737,880.1777,884.1516,648.0172,1500.5006,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20250630,23,11260520,21684.5150,810.4878,403.4668,449.9834,520.2740,741.3618,709.4000,819.9734,...,887.8735,927.9726,749.8991,809.4915,766.2629,1109.3070,886.6321,623.7515,1641.2923,NaN
20250630,23,11260540,16575.0765,555.9794,281.4315,301.2191,384.1538,578.0786,566.1891,705.4743,...,553.8991,747.8099,646.2588,749.3068,593.5265,806.5856,633.7751,500.2872,1384.0752,NaN
20250630,23,11650600,17385.1708,925.4452,388.0889,479.7245,475.7806,601.6947,615.8068,715.6419,...,680.6880,1011.4660,755.9927,773.8965,712.5174,596.9190,440.9832,358.2789,1155.1616,NaN
20250630,23,11680600,25429.5099,1267.1376,1763.1215,2136.7502,637.8767,292.4179,246.0892,307.3759,...,239.8280,585.1152,1420.7323,2076.3054,1058.7179,605.2938,437.6728,366.2053,879.9035,NaN
20250630,23,11260550,12535.5624,367.0228,204.1567,291.5841,291.0006,340.8380,376.3758,566.0460,...,460.6980,641.1608,545.3156,499.1468,491.6846,564.9724,448.1831,355.5981,957.5837,NaN

In [8]:
df = pd.read_csv(
    "C:\Users\Admin\OneDrive\바탕 화면\새 폴더/자전거도로+현황(2002~2012)_20250711121250.csv",
    encoding="cp949")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1327418633.py, line 2)

In [7]:
df

,대여일자,대여소번호,대여소,대여구분코드,성별,연령대,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,2024-12-01,737,737. 장수공원,정기권,NaN,~10대,1,20.97,0.18,790.32,14
1,2024-12-01,1153,"1153. 발산역 1번, 9번 인근 대여소",정기권,NaN,~10대,1,NaN,NaN,1143.00,56
2,2024-12-01,1155,1155. 기쁜우리복지관,정기권,NaN,~10대,1,12.49,0.15,643.66,4
3,2024-12-01,1442,1442. 중랑구청 중화동 별관 앞,정기권,NaN,~10대,3,217.31,1.43,6152.66,42
4,2024-12-01,1160,1160. 양천향교역 7번출구앞,정기권,NaN,~10대,1,28.23,0.30,1296.07,8
...,...,...,...,...,...,...,...,...,...,...,...
1410911,2024-12-31,3500,3500. 군자역2번출구,정기권,M,기타,1,60.00,0.54,2331.01,27
1410912,2024-12-31,3504,3504. 원일교회,정기권,M,기타,1,37.74,0.34,1466.26,70
1410913,2024-12-31,502,502. 자양(뚝섬한강공원)역 1번출구 앞,정기권,M,기타,1,155.05,1.40,6023.60,74
1410914,2024-12-31,723,723. SBS방송국,정기권,M,기타,1,30.51,0.27,1185.26,10
1410915,2024-12-31,726,726. 목동3단지 시내버스정류장,정기권,M,기타,1,26.59,0.20,872.14,6

In [ ]:
df = pd.read_csv("C:\Users\Admin\OneDrive\바탕 화면\새 폴더/유동인구.csv", encoding="cp949")